### ISSUE TITLE
这个要如何使用啊?

### ISSUE THREAD

**Issue by youngallien** [sselecirPyM/Coocoo3D#1]
您好, 这个项目要怎么使用? 直接编译源码吗? 生成失败怎么办?

**Comment by sselecirPyM** [comment]
删掉你编译失败的项目，重新解压源码。
选x64然后运行

**Comment by youngallien** [comment]
![image](https://user-images.githubusercontent.com/53220351/128303801-d952ba46-6fae-4a9a-80ae-985b527b5b30.png)

**Comment by youngallien** [comment]
非常感谢您的回复, 我打开sln选择release, x64, 然后运行的

**Comment by sselecirPyM** [comment]
删掉PSCompileTest.hlsl

**Comment by youngallien** [comment]
![image](https://user-images.githubusercontent.com/53220351/128306650-297c84e3-130f-4baa-9ad1-e179b031b7fb.png)
删掉后, 重新运行

**Comment by sselecirPyM** [comment]
更新下你的VS
